#!/usr/bin/env bash

if [ ! "production" == "$CONTAINER_ENV" ] && [ ! "prod" == "$CONTAINER_ENV" ]; then
    # Enable xdebug

    ## FPM
    ln -sf /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/fpm/conf.d/20-xdebug.ini

    ## CLI
    ln -sf /etc/php/7.1/mods-available/xdebug.ini /etc/php/7.1/cli/conf.d/20-xdebug.ini
else
    # Disable xdebug

    ## FPM
    if [ -e /etc/php/7.1/fpm/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.1/fpm/conf.d/20-xdebug.ini
    fi

    ## CLI
    if [ -e /etc/php/7.1/cli/conf.d/20-xdebug.ini ]; then
        rm -f /etc/php/7.1/cli/conf.d/20-xdebug.ini
    fi
fi

# Config /etc/php/7.1/mods-available/xdebug.ini
sed -i "s/xdebug\.remote_host\=.*/xdebug\.remote_host\=$XDEBUG_HOST/g" /etc/php/7.1/mods-available/xdebug.ini

# If a env-prod file exists as a Docker Secret,
# we'll  use that instead of the one potentially included
if [ -f /run/secrets/env-prod ]; then
    
    # Delete .env file if it exists
    if [ -f /var/www/html/.env ]; then
        rm /var/www/html/.env
    fi
    
    # Symlink .env from the secret file
    ln -sf /run/secrets/env-prod /var/www/html/.env
fi

# Add some fun headers to http responses
sed -i "s/A-Container/$HOSTNAME/g" /etc/nginx/sites-available/default

if [ $# -gt 0 ];then
    # If we passed a command, run it
    exec "$@"
else
    # Otherwise start supervisord
    /usr/bin/supervisord
fi
